name: mailmetodologyervice
services:
  mailservice:
    build:
      context: ..
      dockerfile: Dockerfile
    networks:
      - mailNet
networks:
  mailNet:
    name: mailNet
    driver: bridge
    external: true
    